"""Merged country to languages mapping for countries with 50+ films."""

# Country -> List of accepted languages
# Only includes countries with 50+ films that need language filtering
# Empty countries (< 50 films) are handled in the main script with no filtering
COUNTRY_LANGUAGES = {
    "Argentina": ["Spanish"],
    "Australia": ["English"],
    "Austria": ["German", "English"],
    "Belgium": ["French", "English"],
    "Brazil": ["Portuguese"],
    "Bulgaria": ["English"],
    "Canada": ["English"],
    "Chile": ["Spanish"],
    "China": ["Chinese", "English"],
    "Colombia": ["Spanish", "English"],
    "Croatia": ["Croatian", "Serbian", "English"],
    "Czechia": ["English", "Czech", "German"],
    "Czechoslovakia": ["Czech"],
    "Denmark": ["Danish", "English", "Swedish"],
    "Egypt": ["Arabic"],
    "Estonia": ["Estonian", "Russian", "English"],
    "Finland": ["Finnish", "English"],
    "France": ["French", "English"],
    "Germany": ["English", "German"],
    "Greece": ["Greek (modern)", "English"],
    "Hong Kong": ["Cantonese", "Chinese", "English"],
    "Hungary": ["Hungarian", "English"],
    "Iceland": ["English", "Icelandic"],
    "India": ["Hindi", "Tamil", "Malayalam"],
    "Indonesia": ["Indonesian"],
    "Iran": ["Persian (Farsi)"],
    "Ireland": ["English"],
    "Israel": ["Hebrew (modern)", "English"],
    "Italy": ["Italian", "English", "French"],
    "Japan": ["Japanese"],
    "Lithuania": ["English", "Lithuanian", "French", "Russian"],
    "Luxembourg": ["English", "French"],
    "Malaysia": ["Malay", "English", "Chinese", "Cantonese"],
    "Mexico": ["Spanish", "English"],
    "Morocco": ["Arabic", "English", "French"],
    "Netherlands": ["Dutch", "English"],
    "New Zealand": ["English"],
    "Norway": ["Norwegian", "English", "Swedish"],
    "Peru": ["Spanish", "English", "Quechua"],
    "Philippines": ["Tagalog", "English"],
    "Poland": ["Polish", "English"],
    "Portugal": ["Portuguese", "French", "English"],
    "Qatar": ["Arabic", "English", "Spanish"],
    "Romania": ["English", "Romanian"],
    "Russia": ["Russian", "English"],
    "Serbia": ["Serbian", "English"],
    "Singapore": ["English", "Chinese", "Cantonese"],
    "Slovakia": ["Czech", "English"],
    "South Africa": ["English"],
    "South Korea": ["Korean"],
    "Spain": ["Spanish", "English"],
    "Sweden": ["Swedish", "English"],
    "Switzerland": ["English", "French", "German"],
    "Taiwan": ["Chinese", "English"],
    "Thailand": ["Thai", "English"],
    "Tunisia": ["Arabic", "French"],
    "Turkey": ["Turkish"],
    "UK": ["English"],
    "USA": ["English"],
    "USSR": ["Russian"],
    "Ukraine": ["Russian", "Ukrainian", "English"],
    "United Arab Emirates": ["English", "Arabic"],
    "Uruguay": ["Spanish"],
    "Yugoslavia": ["Serbo-Croatian", "Serbian", "German", "English", "Italian"],
}
